version: '3'

services:
  db:
    image: postgres
    expose:
      - "5432"
  nginx:
    image: nginx:1.13.3-alpine
    volumes:
      - './client/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './client:/ng-app'
    ports:
      - '80:80'
  api:
    build: .
    command: bash run-dev.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  client:
    build: ./client
    ports:
      - '4200:4200'
    volumes:
      - './client/src:/ng-app/src'