version: '3'

services:
  db:
    image: postgres
    expose:
      - "5432"
  api:
    build: .
    command: bash run-dev.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db